# Какие источники тянуть и с какими параметрами
sources:
  dreambank:
    enabled: true
    limit: 50           # сколько страниц/коллекций просматривать (бережно)
  sddb_zenodo:
    enabled: true
    record_id: 11662064 # пример публичной записи с отчётами/метаданными
  dryad:
    - doi: "10.5061/dryad.qbzkh18fr"   # список DOI на Dryad (можно несколько)
  donders:
    - fig_id: "21388722"               # список figshare articles id (можно несколько)

  # RSS/Atom ленты блогов с разрешённой лицензией (CC-BY/автор разрешил).
  # Примеры-заглушки — замените на свои!
  rss:
    - url: "https://example.com/dreams/feed.xml"
      license: "CC-BY-4.0"
    - url: "https://example.org/cc-by-dreams.xml"
      license: "CC-BY-4.0"

  # Google Sheets (удобно для ручной редакции): файл → File → Publish to web → CSV URL
  google_sheets:
    - csv_url: "https://docs.google.com/spreadsheets/d/XXXX/export?format=csv"
      license: "by-owner"

  # Reddit (опционально; требуется OAuth-токены; соблюдаем ToS; берём краткие выдержки)
  reddit:
    enabled: true
    subreddits: ["Dreams"]   # список сабов
    limit: 200               # сколько постов забирать (top/month или hot по простоте)
    mode: "hot"              # hot | new | top

  # Hugging Face datasets (опционально; для продвинутых)
  hf_datasets:
    enabled: true
    names: []                # напр., ["your-user/dreams-corpus"]; требует pip install datasets

  # ВАШ САЙТ (только владелец): вкл. если вы — правообладатель контента
  magickum_owner:
    enabled: false
    start_url: "https://magickum.com/magikum-sonnik"
    domain: "magickum.com"
