name: Build Dreambook Data

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 2 * * *"   # ежедневно 02:17 UTC

jobs:
  etl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Ensure data folder
        run: mkdir -p data

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 html2text tqdm rapidfuzz pyyaml feedparser tldextract
          # опциональные коннекторы:
          pip install praw || true
          pip install datasets || true
          pip install openai || true

      - name: Default sources.yml if missing
        run: |
          if [ ! -f sources.yml ]; then
            cat > sources.yml <<'YAML'
          $(echo "sources:
  dreambank: {enabled: true, limit: 30}
  sddb_zenodo: {enabled: true, record_id: 11662064}
  dryad: [{doi: '10.5061/dryad.qbzkh18fr'}]
  donders: [{fig_id: '21388722'}]
  rss: []
  google_sheets: []
  reddit: {enabled: false, subreddits: ['Dreams'], limit: 100, mode: 'hot'}
  hf_datasets: {enabled: false, names: []}
  magickum_owner: {enabled: false, start_url: 'https://magickum.com/magikum-sonnik', domain: 'magickum.com'}" )
YAML
          fi

      - name: Run ETL v2
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}      # опционально
          OWNER_APPROVED: ${{ secrets.OWNER_APPROVED }}      # "1" если вы владелец и разрешаете сбор
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}  # если включите reddit
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python etl_dreams_v2.py --config sources.yml --out data/dreams_curated.json --outl data/dreams_curated.jsonl

      - name: Commit & push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/dreams_curated.json data/dreams_curated.jsonl || true
          git diff --cached --quiet && echo "No changes" || (git commit -m "ETL v2: update dreambook data" && git push)
