name: UI Tests

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/test-ui.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/test-ui.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test -- --runInBand

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        env:
          CI: 'true'
        run: npm run e2e
